version: '3.8'

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt

services:
  mariadb:
    container_name: mariadb
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-ft_onion:latest
    # ports:
    #   - "8080:80"
    #   - "4242:4242"
    volumes:

    networks:
    # restart: unless-stopped
  

networks:
  ft_onion_network:
    driver: bridge 