# Base Image
#Using Alpine because its more lightweight than Debian
# alpine:3.22 instead of alpine:latest because its more stable version

# FROM alpine:3.22

# # Required Packages
# RUN apk update && apk upgrade && add --no-cache
# 	nginx \
# 	openssl \
# 	curl \
# 	bash \
# 	iproute2 \

# # Create directories for SSL certificates
# RUN mkdir -p /etc/nginx/ssl /var/www/html;
# COPY

# RUN mkdir -p /etc/nginx/ssl \
# 	&& mkdir -p /run/nginx

# COPY conf/server-cert.pem /etc/nginx/ssl/
# COPY conf/server-key.pem /etc/nginx/ssl/

# RUN

# CMD ["ngnix", "-g", "daemon off;"]


FROM debian:bullseye